apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tan-dara2643-dara-react-certificate
  namespace: tan-dara2643-dara-react
spec:
  secretName: tan-dara2643-dara-react-secret-tls
  commonName: tan-dara2643-dara-react.assessify.org
  dnsNames:
  - tan-dara2643-dara-react.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
